## A1. Imports and settings

In [ ]:
import importlib
from pathlib import Path
import pandas as pd
import sys
import subprocess
from check_number_of_files import count_folders, check_num_dcm_report, patients_with_more_than_1_txt
from labelling.Build_disease_vocab import *
from labelling.scan_disease_v2 import main
import labelling.count_positive_cases as counter

importlib.reload(counter)
count_main = counter.main
from labelling.build_prognosis_labels import main as prognosis_main

### A1.1. Path declaration to all directories

In [68]:
path1 = Path(r"C:\Users\Zila\Downloads\BN5212\MIMIC-CXR\p10\p10")
project_dir = Path(r"C:\Users\Zila\Downloads\BN5212\midterm_prognosis")
labelling_dir = project_dir / "labelling"
vocab_path = labelling_dir / "disease_vocab" / "unique_diseases.csv"
patients_path = labelling_dir / "cxr_labels" / "patients_with_more_than_1_txt.csv"
output_path = labelling_dir / "cxr_labels_selected_everpositive"
prognosis_path = labelling_dir / "prognosis_labels"
hybrid_path = labelling_dir / "prognosis_labels_hybrid"

## A2. Checking the count of Patients, Dicom x-ray images, and Reports

In [4]:
print("Folders in MIMIC-cxr path:", count_folders(path1))
check_num_dcm_report(path1)

Folders in MIMIC-cxr path: 1000
p10000032: 7 DICOM images, 4 reports
p10000764: 3 DICOM images, 1 reports
p10000898: 5 DICOM images, 2 reports
p10000935: 10 DICOM images, 6 reports
p10000980: 16 DICOM images, 9 reports
p10001038: 3 DICOM images, 1 reports
p10001122: 5 DICOM images, 2 reports
p10001176: 5 DICOM images, 2 reports
p10001217: 3 DICOM images, 2 reports
p10001401: 10 DICOM images, 6 reports
p10001851: 2 DICOM images, 1 reports
p10001884: 55 DICOM images, 31 reports
p10002013: 15 DICOM images, 9 reports
p10002131: 2 DICOM images, 1 reports
p10002157: 2 DICOM images, 1 reports
p10002177: 2 DICOM images, 1 reports
p10002221: 2 DICOM images, 1 reports
p10002428: 34 DICOM images, 28 reports
p10002430: 9 DICOM images, 4 reports
p10002557: 2 DICOM images, 1 reports
p10002559: 5 DICOM images, 2 reports
p10002661: 2 DICOM images, 1 reports
p10002804: 2 DICOM images, 1 reports
p10002930: 2 DICOM images, 1 reports
p10003019: 30 DICOM images, 17 reports
p10003052: 3 DICOM images, 1 reports
p10003255: 2 DICOM images, 1 reports
p10003299: 4 DICOM images, 2 reports
p10003400: 35 DICOM images, 28 reports
p10003412: 2 DICOM images, 1 reports
p10003502: 12 DICOM images, 8 reports
p10003637: 5 DICOM images, 3 reports
p10003956: 2 DICOM images, 1 reports
p10004235: 10 DICOM images, 8 reports
p10004322: 2 DICOM images, 1 reports
p10004457: 2 DICOM images, 1 reports
p10004720: 2 DICOM images, 1 reports
p10004749: 2 DICOM images, 1 reports
p10005001: 2 DICOM images, 1 reports
p10005024: 3 DICOM images, 2 reports
p10005329: 2 DICOM images, 1 reports
p10005368: 3 DICOM images, 3 reports
p10005749: 11 DICOM images, 6 reports
p10005858: 4 DICOM images, 2 reports
p10005866: 5 DICOM images, 4 reports
p10006023: 2 DICOM images, 1 reports
p10006431: 4 DICOM images, 2 reports
p10006457: 4 DICOM images, 2 reports
p10006501: 2 DICOM images, 1 reports
p10006692: 2 DICOM images, 1 reports
p10007058: 2 DICOM images, 2 reports
p10007134: 2 DICOM images, 1 reports
p10007326: 2 DICOM images, 1 reports
p10007795: 12 DICOM images, 8 reports
p10007920: 6 DICOM images, 3 reports
p10007928: 4 DICOM images, 4 reports
p10008064: 2 DICOM images, 1 reports
p10008179: 2 DICOM images, 1 reports
p10008304: 5 DICOM images, 2 reports
p10008493: 2 DICOM images, 1 reports
p10008816: 4 DICOM images, 2 reports
p10008922: 2 DICOM images, 1 reports
p10009049: 7 DICOM images, 5 reports
p10009614: 2 DICOM images, 1 reports
p10010150: 4 DICOM images, 2 reports
p10010231: 4 DICOM images, 3 reports
p10010253: 2 DICOM images, 1 reports
p10010440: 5 DICOM images, 3 reports
p10010471: 4 DICOM images, 2 reports
p10010635: 1 DICOM images, 1 reports
p10010638: 2 DICOM images, 1 reports
p10010867: 23 DICOM images, 20 reports
p10010920: 2 DICOM images, 1 reports
p10010961: 2 DICOM images, 1 reports
p10011126: 5 DICOM images, 2 reports
p10011169: 2 DICOM images, 1 reports
p10011365: 13 DICOM images, 9 reports
p10011466: 2 DICOM images, 1 reports
p10011607: 22 DICOM images, 11 reports
p10011668: 13 DICOM images, 7 reports
p10011855: 2 DICOM images, 1 reports
p10011938: 11 DICOM images, 7 reports
p10012261: 21 DICOM images, 17 reports
p10012292: 10 DICOM images, 8 reports
p10012438: 2 DICOM images, 1 reports
p10012498: 2 DICOM images, 1 reports
p10012569: 3 DICOM images, 1 reports
p10012768: 4 DICOM images, 3 reports
p10012853: 6 DICOM images, 4 reports
p10013094: 2 DICOM images, 1 reports
p10013324: 2 DICOM images, 1 reports
p10013502: 4 DICOM images, 2 reports
p10013569: 15 DICOM images, 14 reports
p10013643: 12 DICOM images, 8 reports
p10013653: 28 DICOM images, 13 reports
p10013866: 3 DICOM images, 1 reports
p10014078: 2 DICOM images, 2 reports
p10014309: 3 DICOM images, 1 reports
p10014354: 5 DICOM images, 3 reports
p10014378: 2 DICOM images, 1 reports
p10014532: 3 DICOM images, 1 reports
p10014577: 1 DICOM images, 1 reports
p10014610: 15 DICOM images, 12 reports
p10014729: 14 DICOM images, 10 reports
p10014756: 1 DICOM images, 1 reports
p10014762: 2 DICOM images, 1 reports
p10014765: 4 DICOM images, 2 reports
p10014967: 4 DICOM images, 2 reports
p10015048: 12 DICOM images, 6 reports
p10015129: 6 DICOM images, 3 reports
p10015272: 1 DICOM images, 1 reports
p10015487: 5 DICOM images, 2 reports
p10015701: 2 DICOM images, 1 reports
p10015725: 2 DICOM images, 1 reports
p10015785: 4 DICOM images, 2 reports
p10015824: 2 DICOM images, 1 reports
p10015860: 11 DICOM images, 5 reports
p10015931: 20 DICOM images, 13 reports
p10016084: 3 DICOM images, 2 reports
p10016367: 4 DICOM images, 2 reports
p10016742: 12 DICOM images, 11 reports
p10016810: 1 DICOM images, 1 reports
p10016832: 2 DICOM images, 1 reports
p10017492: 2 DICOM images, 1 reports
p10017972: 2 DICOM images, 1 reports
p10018052: 2 DICOM images, 1 reports
p10018078: 1 DICOM images, 1 reports
p10018081: 41 DICOM images, 36 reports
p10018169: 2 DICOM images, 1 reports
p10018205: 6 DICOM images, 3 reports
p10018286: 3 DICOM images, 1 reports
p10018328: 3 DICOM images, 3 reports
p10018423: 6 DICOM images, 4 reports
p10018684: 2 DICOM images, 1 reports
p10018712: 5 DICOM images, 2 reports
p10018852: 2 DICOM images, 1 reports
p10019003: 10 DICOM images, 10 reports
p10019061: 1 DICOM images, 1 reports
p10019096: 2 DICOM images, 1 reports
p10019108: 2 DICOM images, 1 reports
p10019385: 7 DICOM images, 4 reports
p10019517: 4 DICOM images, 2 reports
p10019568: 6 DICOM images, 4 reports
p10019593: 2 DICOM images, 1 reports
p10019777: 10 DICOM images, 6 reports
p10020306: 6 DICOM images, 3 reports
p10020435: 4 DICOM images, 2 reports
p10020740: 26 DICOM images, 20 reports
p10020843: 2 DICOM images, 1 reports
p10020852: 5 DICOM images, 2 reports
p10020944: 16 DICOM images, 12 reports
p10021348: 3 DICOM images, 2 reports
p10021395: 1 DICOM images, 1 reports
p10021487: 29 DICOM images, 23 reports
p10021666: 2 DICOM images, 2 reports
p10021704: 2 DICOM images, 1 reports
p10021927: 22 DICOM images, 16 reports
p10021938: 6 DICOM images, 3 reports
p10022037: 6 DICOM images, 2 reports
p10022041: 5 DICOM images, 3 reports
p10022373: 8 DICOM images, 5 reports
p10023020: 1 DICOM images, 1 reports
p10023117: 25 DICOM images, 17 reports
p10023239: 2 DICOM images, 1 reports
p10023708: 6 DICOM images, 3 reports
p10024018: 2 DICOM images, 1 reports
p10024048: 2 DICOM images, 1 reports
p10024120: 2 DICOM images, 1 reports
p10024130: 1 DICOM images, 1 reports
p10024170: 2 DICOM images, 1 reports
p10024331: 18 DICOM images, 6 reports
p10024913: 9 DICOM images, 5 reports
p10024982: 36 DICOM images, 25 reports
p10024984: 2 DICOM images, 1 reports
p10025139: 7 DICOM images, 3 reports
p10025268: 9 DICOM images, 4 reports
p10025458: 3 DICOM images, 1 reports
p10025463: 1 DICOM images, 1 reports
p10025630: 4 DICOM images, 2 reports
p10025647: 16 DICOM images, 6 reports
p10025759: 2 DICOM images, 1 reports
p10025791: 2 DICOM images, 1 reports
p10025841: 2 DICOM images, 1 reports
p10026055: 4 DICOM images, 1 reports
p10026077: 3 DICOM images, 1 reports
p10026165: 3 DICOM images, 1 reports
p10026255: 22 DICOM images, 12 reports
p10026263: 10 DICOM images, 3 reports
p10026354: 3 DICOM images, 2 reports
p10026404: 2 DICOM images, 1 reports
p10026698: 4 DICOM images, 2 reports
p10026754: 2 DICOM images, 1 reports
p10026950: 3 DICOM images, 2 reports
p10027100: 15 DICOM images, 7 reports
p10027557: 2 DICOM images, 1 reports
p10027602: 14 DICOM images, 11 reports
p10027672: 2 DICOM images, 1 reports
p10027957: 13 DICOM images, 7 reports
p10028012: 2 DICOM images, 1 reports
p10028098: 2 DICOM images, 1 reports
p10028125: 2 DICOM images, 1 reports
p10028159: 1 DICOM images, 1 reports
p10028306: 3 DICOM images, 1 reports
p10028480: 9 DICOM images, 5 reports
p10028683: 2 DICOM images, 1 reports
p10029038: 1 DICOM images, 1 reports
p10029106: 1 DICOM images, 1 reports
p10029291: 17 DICOM images, 13 reports
p10029411: 4 DICOM images, 2 reports
p10029874: 13 DICOM images, 8 reports
p10030046: 2 DICOM images, 1 reports
p10030487: 10 DICOM images, 6 reports
p10030579: 2 DICOM images, 1 reports
p10030630: 2 DICOM images, 1 reports
p10030753: 17 DICOM images, 9 reports
p10030863: 2 DICOM images, 1 reports
p10031358: 2 DICOM images, 1 reports
p10031687: 5 DICOM images, 3 reports
p10031816: 4 DICOM images, 2 reports
p10031850: 6 DICOM images, 4 reports
p10032409: 40 DICOM images, 29 reports
p10032608: 2 DICOM images, 1 reports
p10032725: 2 DICOM images, 2 reports
p10032890: 2 DICOM images, 1 reports
p10033106: 2 DICOM images, 1 reports
p10033290: 2 DICOM images, 1 reports
p10033409: 2 DICOM images, 1 reports
p10033552: 11 DICOM images, 4 reports
p10033760: 1 DICOM images, 1 reports
p10034062: 2 DICOM images, 1 reports
p10034469: 2 DICOM images, 1 reports
p10034899: 2 DICOM images, 1 reports
p10035301: 2 DICOM images, 1 reports
p10035631: 16 DICOM images, 9 reports
p10035667: 2 DICOM images, 1 reports
p10035780: 8 DICOM images, 5 reports
p10036086: 4 DICOM images, 2 reports
p10036104: 2 DICOM images, 1 reports
p10036161: 2 DICOM images, 1 reports
p10036628: 2 DICOM images, 1 reports
p10036909: 2 DICOM images, 1 reports
p10037020: 6 DICOM images, 4 reports
p10037432: 4 DICOM images, 2 reports
p10037598: 3 DICOM images, 1 reports
p10037602: 4 DICOM images, 2 reports
p10037769: 2 DICOM images, 1 reports
p10037818: 2 DICOM images, 1 reports
p10037928: 18 DICOM images, 11 reports
p10037967: 8 DICOM images, 4 reports
p10038332: 4 DICOM images, 2 reports
p10038828: 2 DICOM images, 1 reports
p10038999: 11 DICOM images, 10 reports
p10039272: 36 DICOM images, 18 reports
p10039302: 6 DICOM images, 5 reports
p10039360: 2 DICOM images, 1 reports
p10039387: 2 DICOM images, 1 reports
p10039643: 2 DICOM images, 1 reports
p10039708: 28 DICOM images, 24 reports
p10039913: 2 DICOM images, 1 reports
p10039953: 2 DICOM images, 1 reports
p10039959: 2 DICOM images, 1 reports
p10040025: 8 DICOM images, 4 reports
p10040082: 2 DICOM images, 1 reports
p10040221: 2 DICOM images, 1 reports
p10040284: 2 DICOM images, 1 reports
p10040602: 3 DICOM images, 1 reports
p10040604: 2 DICOM images, 1 reports
p10040622: 2 DICOM images, 1 reports
p10040631: 4 DICOM images, 2 reports
p10040721: 1 DICOM images, 1 reports
p10040768: 2 DICOM images, 1 reports
p10040884: 3 DICOM images, 2 reports
p10041196: 3 DICOM images, 1 reports
p10041312: 3 DICOM images, 1 reports
p10041408: 3 DICOM images, 2 reports
p10041918: 4 DICOM images, 2 reports
p10042037: 2 DICOM images, 1 reports
p10042350: 2 DICOM images, 1 reports
p10042615: 2 DICOM images, 1 reports
p10042769: 1 DICOM images, 1 reports
p10042810: 6 DICOM images, 4 reports
p10042998: 2 DICOM images, 1 reports
p10043050: 2 DICOM images, 1 reports
p10043103: 2 DICOM images, 1 reports
p10043115: 4 DICOM images, 2 reports
p10043139: 2 DICOM images, 1 reports
p10043177: 4 DICOM images, 2 reports
p10043321: 11 DICOM images, 6 reports
p10043339: 2 DICOM images, 1 reports
p10043423: 4 DICOM images, 2 reports
p10043514: 2 DICOM images, 1 reports
p10043646: 3 DICOM images, 2 reports
p10043750: 1 DICOM images, 1 reports
p10044096: 15 DICOM images, 6 reports
p10044189: 6 DICOM images, 4 reports
p10044316: 4 DICOM images, 2 reports
p10044391: 2 DICOM images, 1 reports
p10044419: 2 DICOM images, 1 reports
p10044859: 2 DICOM images, 1 reports
p10045064: 2 DICOM images, 1 reports
p10045099: 2 DICOM images, 1 reports
p10045574: 2 DICOM images, 1 reports
p10045779: 3 DICOM images, 1 reports
p10045929: 12 DICOM images, 9 reports
p10046041: 2 DICOM images, 1 reports
p10046166: 12 DICOM images, 6 reports
p10046241: 4 DICOM images, 2 reports
p10046282: 2 DICOM images, 1 reports
p10046503: 2 DICOM images, 1 reports
p10046592: 6 DICOM images, 3 reports
p10046679: 17 DICOM images, 13 reports
p10046922: 2 DICOM images, 1 reports
p10047172: 13 DICOM images, 6 reports
p10047766: 7 DICOM images, 4 reports
p10047944: 2 DICOM images, 1 reports
p10048001: 23 DICOM images, 15 reports
p10048244: 19 DICOM images, 14 reports
p10048451: 14 DICOM images, 7 reports
p10048522: 4 DICOM images, 2 reports
p10048703: 2 DICOM images, 1 reports
p10048710: 5 DICOM images, 2 reports
p10048900: 2 DICOM images, 1 reports
p10048986: 15 DICOM images, 6 reports
p10049334: 5 DICOM images, 3 reports
p10049341: 6 DICOM images, 3 reports
p10049782: 3 DICOM images, 1 reports
p10049851: 2 DICOM images, 1 reports
p10049897: 2 DICOM images, 1 reports
p10049902: 12 DICOM images, 6 reports
p10050106: 1 DICOM images, 1 reports
p10050154: 2 DICOM images, 1 reports
p10050205: 1 DICOM images, 1 reports
p10050755: 14 DICOM images, 8 reports
p10050790: 2 DICOM images, 1 reports
p10051043: 13 DICOM images, 12 reports
p10051242: 2 DICOM images, 1 reports
p10051658: 2 DICOM images, 1 reports
p10051825: 1 DICOM images, 1 reports
p10051990: 4 DICOM images, 2 reports
p10052047: 4 DICOM images, 1 reports
p10052077: 2 DICOM images, 1 reports
p10052277: 8 DICOM images, 4 reports
p10052407: 2 DICOM images, 1 reports
p10052802: 2 DICOM images, 1 reports
p10052926: 16 DICOM images, 8 reports
p10052992: 4 DICOM images, 2 reports
p10053000: 2 DICOM images, 1 reports
p10053184: 1 DICOM images, 1 reports
p10053207: 3 DICOM images, 2 reports
p10053357: 2 DICOM images, 1 reports
p10053611: 6 DICOM images, 3 reports
p10053782: 2 DICOM images, 1 reports
p10053918: 3 DICOM images, 1 reports
p10054277: 6 DICOM images, 4 reports
p10054639: 6 DICOM images, 3 reports
p10055034: 13 DICOM images, 6 reports
p10055072: 2 DICOM images, 1 reports
p10055344: 9 DICOM images, 6 reports
p10055361: 13 DICOM images, 8 reports
p10055694: 23 DICOM images, 15 reports
p10056037: 1 DICOM images, 1 reports
p10056209: 2 DICOM images, 1 reports
p10056223: 29 DICOM images, 16 reports
p10056441: 2 DICOM images, 1 reports
p10056612: 4 DICOM images, 2 reports
p10057005: 5 DICOM images, 5 reports
p10057009: 5 DICOM images, 2 reports
p10057070: 1 DICOM images, 1 reports
p10057178: 3 DICOM images, 1 reports
p10057482: 2 DICOM images, 1 reports
p10057559: 2 DICOM images, 1 reports
p10057763: 3 DICOM images, 2 reports
p10058033: 3 DICOM images, 1 reports
p10058116: 2 DICOM images, 1 reports
p10058150: 3 DICOM images, 2 reports
p10058575: 14 DICOM images, 14 reports
p10058642: 2 DICOM images, 1 reports
p10058697: 2 DICOM images, 1 reports
p10058813: 2 DICOM images, 1 reports
p10058910: 2 DICOM images, 1 reports
p10058974: 5 DICOM images, 4 reports
p10059615: 2 DICOM images, 1 reports
p10059653: 2 DICOM images, 1 reports
p10059690: 6 DICOM images, 3 reports
p10060142: 6 DICOM images, 6 reports
p10060204: 4 DICOM images, 2 reports
p10060703: 3 DICOM images, 2 reports
p10060863: 5 DICOM images, 2 reports
p10061358: 2 DICOM images, 1 reports
p10061468: 2 DICOM images, 1 reports
p10061593: 6 DICOM images, 3 reports
p10061731: 5 DICOM images, 2 reports
p10062020: 7 DICOM images, 4 reports
p10062501: 4 DICOM images, 2 reports
p10062522: 1 DICOM images, 1 reports
p10062615: 2 DICOM images, 1 reports
p10062617: 18 DICOM images, 10 reports
p10062692: 8 DICOM images, 4 reports
p10062981: 6 DICOM images, 2 reports
p10063280: 4 DICOM images, 2 reports
p10063534: 2 DICOM images, 2 reports
p10063762: 2 DICOM images, 1 reports
p10063856: 7 DICOM images, 4 reports
p10064049: 48 DICOM images, 27 reports
p10064124: 1 DICOM images, 1 reports
p10064176: 3 DICOM images, 1 reports
p10064390: 6 DICOM images, 6 reports
p10064678: 12 DICOM images, 7 reports
p10064818: 2 DICOM images, 1 reports
p10065125: 2 DICOM images, 2 reports
p10065220: 2 DICOM images, 1 reports
p10065354: 2 DICOM images, 2 reports
p10065383: 39 DICOM images, 35 reports
p10065615: 5 DICOM images, 3 reports
p10065656: 1 DICOM images, 1 reports
p10065685: 2 DICOM images, 1 reports
p10065767: 12 DICOM images, 8 reports
p10065864: 2 DICOM images, 1 reports
p10065990: 5 DICOM images, 3 reports
p10065997: 4 DICOM images, 2 reports
p10066039: 1 DICOM images, 1 reports
p10066209: 6 DICOM images, 6 reports
p10066384: 2 DICOM images, 1 reports
p10066415: 4 DICOM images, 1 reports
p10066489: 2 DICOM images, 1 reports
p10066767: 2 DICOM images, 1 reports
p10067530: 4 DICOM images, 2 reports
p10067562: 2 DICOM images, 1 reports
p10067702: 11 DICOM images, 7 reports
p10068026: 4 DICOM images, 2 reports
p10068137: 2 DICOM images, 1 reports
p10068152: 1 DICOM images, 1 reports
p10068157: 2 DICOM images, 1 reports
p10068304: 16 DICOM images, 12 reports
p10068741: 2 DICOM images, 2 reports
p10068880: 4 DICOM images, 2 reports
p10068987: 2 DICOM images, 1 reports
p10069423: 6 DICOM images, 5 reports
p10069960: 2 DICOM images, 1 reports
p10070011: 2 DICOM images, 1 reports
p10070226: 2 DICOM images, 1 reports
p10070288: 4 DICOM images, 2 reports
p10070311: 4 DICOM images, 2 reports
p10070330: 6 DICOM images, 2 reports
p10070592: 8 DICOM images, 3 reports
p10070614: 7 DICOM images, 3 reports
p10070626: 2 DICOM images, 1 reports
p10070735: 2 DICOM images, 1 reports
p10070928: 17 DICOM images, 10 reports
p10070999: 1 DICOM images, 1 reports
p10071070: 1 DICOM images, 1 reports
p10071281: 10 DICOM images, 7 reports
p10071403: 13 DICOM images, 11 reports
p10071620: 4 DICOM images, 2 reports
p10071690: 2 DICOM images, 1 reports
p10071766: 3 DICOM images, 1 reports
p10071821: 2 DICOM images, 1 reports
p10071869: 11 DICOM images, 9 reports
p10072153: 6 DICOM images, 4 reports
p10072167: 11 DICOM images, 4 reports
p10072264: 3 DICOM images, 2 reports
p10072559: 2 DICOM images, 1 reports
p10072890: 1 DICOM images, 1 reports
p10072945: 3 DICOM images, 2 reports
p10073182: 4 DICOM images, 2 reports
p10073336: 4 DICOM images, 2 reports
p10073544: 2 DICOM images, 1 reports
p10073646: 4 DICOM images, 3 reports
p10073847: 25 DICOM images, 14 reports
p10074282: 8 DICOM images, 5 reports
p10074321: 4 DICOM images, 2 reports
p10074323: 4 DICOM images, 4 reports
p10074434: 8 DICOM images, 4 reports
p10074556: 5 DICOM images, 5 reports
p10074567: 2 DICOM images, 1 reports
p10074605: 3 DICOM images, 1 reports
p10074649: 2 DICOM images, 1 reports
p10074908: 4 DICOM images, 4 reports
p10075002: 2 DICOM images, 1 reports
p10075034: 2 DICOM images, 1 reports
p10075506: 1 DICOM images, 1 reports
p10075629: 2 DICOM images, 1 reports
p10075925: 2 DICOM images, 1 reports
p10076095: 2 DICOM images, 1 reports
p10076144: 7 DICOM images, 3 reports
p10076263: 10 DICOM images, 5 reports
p10076272: 2 DICOM images, 1 reports
p10076492: 1 DICOM images, 1 reports
p10076526: 12 DICOM images, 10 reports
p10076549: 2 DICOM images, 1 reports
p10076616: 1 DICOM images, 1 reports
p10076617: 9 DICOM images, 5 reports
p10076958: 48 DICOM images, 31 reports
p10077018: 2 DICOM images, 1 reports
p10077298: 4 DICOM images, 2 reports
p10077619: 2 DICOM images, 1 reports
p10078008: 1 DICOM images, 1 reports
p10078072: 8 DICOM images, 5 reports
p10078115: 20 DICOM images, 18 reports
p10078297: 2 DICOM images, 1 reports
p10078480: 3 DICOM images, 2 reports
p10078555: 2 DICOM images, 1 reports
p10078805: 10 DICOM images, 3 reports
p10079117: 4 DICOM images, 2 reports
p10079290: 4 DICOM images, 2 reports
p10079355: 2 DICOM images, 1 reports
p10079431: 2 DICOM images, 1 reports
p10079467: 4 DICOM images, 2 reports
p10079807: 2 DICOM images, 1 reports
p10079964: 2 DICOM images, 1 reports
p10080299: 2 DICOM images, 1 reports
p10080392: 2 DICOM images, 1 reports
p10080421: 2 DICOM images, 2 reports
p10080443: 3 DICOM images, 2 reports
p10080527: 2 DICOM images, 1 reports
p10080679: 2 DICOM images, 1 reports
p10080695: 8 DICOM images, 3 reports
p10080928: 6 DICOM images, 4 reports
p10080961: 8 DICOM images, 6 reports
p10081045: 4 DICOM images, 2 reports
p10081245: 4 DICOM images, 2 reports
p10081525: 10 DICOM images, 6 reports
p10081869: 9 DICOM images, 6 reports
p10081891: 6 DICOM images, 3 reports
p10082014: 13 DICOM images, 9 reports
p10082543: 4 DICOM images, 2 reports
p10082560: 8 DICOM images, 6 reports
p10082895: 2 DICOM images, 1 reports
p10082986: 1 DICOM images, 1 reports
p10083538: 2 DICOM images, 1 reports
p10083678: 2 DICOM images, 1 reports
p10083708: 4 DICOM images, 2 reports
p10083754: 8 DICOM images, 5 reports
p10083833: 4 DICOM images, 2 reports
p10084055: 2 DICOM images, 1 reports

### A2.1. Out of those patients, how many have more than 1 txt file? (i.e. more than 1 report)

In [13]:
count, patient_list = patients_with_more_than_1_txt(path1)
print(f"Patients with more than 1 x-ray visits: {count}")

Patients with more than 1 x-ray visits: 506

In [10]:
patient_list = pd.DataFrame(patient_list, columns=["Patient"])
patient_list.head()

     Patient
0  p10000032
1  p10000898
2  p10000935
3  p10000980
4  p10001122

In [11]:
patient_list.to_csv("patients_with_more_than_1_txt.csv", index=False)

#to do: add figure like the one generated by sahana to see the plot count

## A3. From those patients, we will label based on what disease they have

### A3.1. Firstly, we need to build the disease vocab. We obtained it from d_icd_diagnoses.csv in MIMIC-IV

In [14]:
diagnosis_path = Path("C:\\Users\\Zila\\Downloads\\BN5212\\MIMIC-IV\\3.1\\hosp\\d_icd_diagnoses.csv")

In [18]:
dia_df= load_icd_diagnoses(diagnosis_path)
mapping, labels = load_icd_to_phecode_mapping()
mapped = map_icd_to_phecode(dia_df, mapping, labels)
disease_list = drop_unmapped(mapped)

In [19]:
print(f"Unique mapped disease/phenotype names: {len(disease_list)}")
print(disease_list[:30])

Unique mapped disease/phenotype names: 3544
['(Idiopathic) normal pressure hydrocephalus', '3-methylglutaconic aciduria*', '46, XX/46, XY*', 'ABO isoimmunization of newborn', 'ANCA-associated vasculitides*', 'Abdominal aortic aneurysm', 'Abdominal migraine*', 'Abdominal or pelvic swelling, mass, or lump', 'Abdominal pain', 'Abdominal pregnancy', 'Abdominal rigidity', 'Abdominal tenderness', 'Abnormal Papanicolaou smear', 'Abnormal auditory function study', 'Abnormal blood-gas level', 'Abnormal bowel sounds and visible peristalsis', 'Abnormal cardiac sounds', 'Abnormal coagulation profile', 'Abnormal cytological findings in specimens from genital organs', 'Abnormal digit morphology', 'Abnormal electrocardiogram [ECG] [EKG]', 'Abnormal electroencephalogram [EEG]', 'Abnormal findings on antenatal screening of mother', 'Abnormal findings on diagnostic imaging of heart and coronary circulation', 'Abnormal findings on diagnostic imaging of lung', 'Abnormal findings on diagnostic imaging of skull and head', 'Abnormal findings on diagnostic imaging of the digestive tract', 'Abnormal findings on diagnostic test of central nervous system', 'Abnormal findings on examination of blood', 'Abnormal findings on neonatal screening']

### A3.2. Save the unique diseases vocab into a csv file

In [21]:
pd.DataFrame({"disease": disease_list}).to_csv("labelling/disease_vocab/unique_diseases.csv", index=False)

### A3.1. Now, we scan the reports in cxr that has any of the disease in the vocab we built

In [34]:
main([
    "--vocab", str(vocab_path),
    "--patients", str(patients_path),
    "--reports", str(path1),
    "--skip-uncertain-after-positive",
    "--out", str(output_path),
])

Patient filter: 506 requested, 506 with reports found.
Reading dates from DICOM headers (image pixels are not loaded).
Reports without dates: 0; these remain eligible for review.
Matcher: regex fallback (install flashtext for faster matching); vocabulary: 3544; reports: 2857
Scanned 500/2857
Scanned 1000/2857
Scanned 1500/2857
Scanned 2000/2857
Scanned 2500/2857
Scanned 2857/2857
Saved results to C:\Users\Zila\Downloads\BN5212\midterm_prognosis\labelling\cxr_labels_selected_everpositive
Uncertain reviews skipped after an earlier positive: 78
Labels are sparse: missing rows are NOT negative labels. Check report_summary.
Review samples of positives, negatives, and no_matches as well as review_queue.

### A3.2. Afterwards, we look at the positive diseases labels, and pick 5 of the most abundant

In [40]:
labels_path = output_path / "study_labels.csv"
reviews_path = output_path / "review_queue.csv"
counts_path = output_path / "disease_positive_counts.csv"

In [47]:
count_main([
    "--labels", str(labels_path),
    "--reviews", str(reviews_path),
    "--vocab", str(vocab_path),
    "--out", str(counts_path),
])

Disease                                              Patients    Reports
Pleural effusion                                          167        415
Cardiomegaly                                              155        364
Edema                                                     139        363
Pneumonia                                                 130        225
Pulmonary edema                                           119        277
Fluid overload                                             39         44
Fractures                                                  29         61
Emphysema                                                  28         54
Scoliosis                                                  18         33
Hernia                                                     14         28
Hypertension                                                9          9
Term                                                        8          8
Loss of height                                              7          7
Pulmonary fibrosis                                          6         18
Aspiration pneumonia                                        5          5
Kyphosis                                                    4          6
Bronchiectasis                                              4          4
Bronchitis                                                  3          3
Heart failure                                               3          3
Pulmonary embolism                                          3          3
Pulmonary hypertension                                      3          3
Ileus                                                       2          3
Sarcoidosis                                                 2          3
Spondylosis                                                 2          3
Cough                                                       2          2
Goiter                                                      2          2
Hypersensitivity pneumonitis                                2          2
Pain                                                        2          2
Tachycardia                                                 2          2
Cervical rib                                                1          2
Cryptogenic organizing pneumonia                            1          2
Acute pulmonary edema                                       1          1
Aortic dissection                                           1          1
Ascites                                                     1          1
Bronchospasm                                                1          1
Cardiomyopathy                                              1          1
Fever                                                       1          1
Intestinal obstruction                                      1          1
Intussusception                                             1          1
Myelodysplastic syndrome                                    1          1
Pectus excavatum                                            1          1
Sepsis                                                      1          1
Septic embolism                                             1          1
Splenomegaly                                                1          1
Vomiting                                                    1          1
Wheezing                                                    1          1
(Idiopathic) normal pressure hydrocephalus                  0          0
3-methylglutaconic aciduria*                                0          0
46, XX/46, XY*                                              0          0
ABO isoimmunization of newborn                              0          0
ANCA-associated vasculitides*                               0          0
Abdominal aortic aneurysm                                   0          0
Abdominal migraine*                                         0          0
Abdominal or pelvic swelling, mass, or lump                 0          0
Abdominal pain                                              0          0
Abdominal pregnancy                                         0          0
Abdominal rigidity                                          0          0
Abdominal tenderness                                        0          0
Abnormal Papanicolaou smear                                 0          0
Abnormal auditory function study                            0          0
Abnormal blood-gas level                                    0          0
Abnormal bowel sounds and visible peristalsis               0          0
Abnormal cardiac sounds                                     0          0
Abnormal coagulation profile                                0          0
Abnormal cytological findings in specimens from genital organs          0          0
Abnormal digit morphology                                   0          0
Abnormal electrocardiogram [ECG] [EKG]                      0          0
Abnormal electroencephalogram [EEG]                         0          0
Abnormal findings on antenatal screening of mother          0          0
Abnormal findings on diagnostic imaging of heart and coronary circulation          0          0
Abnormal findings on diagnostic imaging of lung             0          0
Abnormal findings on diagnostic imaging of skull and head          0          0
Abnormal findings on diagnostic imaging of the digestive tract          0          0
Abnormal findings on diagnostic test of central nervous system          0          0
Abnormal findings on examination of blood                   0          0
Abnormal findings on neonatal screening                     0          0
Abnormal findings on radiological and other examination of genitourinary organs          0          0
Abnormal forces of labor                                    0          0
Abnormal glucose                                            0          0
Abnormal glucose complicating pregnancy                     0          0
Abnormal head movements*                                    0          0
Abnormal innervation syndrome of eyelid                     0          0
Abnormal intraocular pressure                               0          0
Abnormal involuntary movements                              0          0
Abnormal level of blood mineral*                            0          0
Abnormal levels of other serum enzymes                      0          0
Abnormal mammogram                                          0          0
Abnormal plasma viscosity*                                  0          0
Abnormal posture                                            0          0
Abnormal products of conception                             0          0
Abnormal reflex                                             0          0
Abnormal results of cardiovascular function studies          0          0
Abnormal results of endocrine function studies (excluding thyroid)          0          0
Abnormal results of function studies of eye                 0          0
Abnormal results of function studies of peripheral nervous system          0          0
Abnormal results of function study of kidney                0          0
Abnormal results of pulmonary function studies              0          0
Abnormal serum enzyme levels                                0          0
Abnormal sputum                                             0          0
Abnormal thyroid function studies                           0          0
Abnormal tumor markers                                      0          0
Abnormal vestibular function study                          0          0
Abnormal weight gain                                        0          0
Abnormal weight loss                                        0          0
Abnormalities of breathing                                  0          0
Abnormalities of ear ossicles                               0          0
Abnormalities of gravid uterus                              0          0
Abnormalities of heart beat                                 0          0
Abnormalities of size and form of teeth                     0          0
Abnormalities of the hair                                   0          0
Abnormality in fetal heart rate and rhythm complicating labor and delivery*          0          0
Abnormality in fetal heart rate or rhythm                   0          0
Abnormality of albumin*                                     0          0
Abnormality of alphafetoprotein*                            0          0
Abnormality of gait                                         0          0
Abnormality of gait and mobility                            0          0
Abnormality of globulin*                                    0          0
Abnormality of red blood cells                              0          0
Abnormality of secretion of gastrin                         0          0
Abnormality of secretion of glucagon                        0          0
Abnormality of the lymph nodes                              0          0
Abnormality of the peritoneum                               0          0
Abnormality of the urachus                                  0          0
Abnormality of urination                                    0          0
Abscess of eyelid                                           0          0
Abscess of liver                                            0          0
Abscess of lung and mediastinum                             0          0
Abscess of spleen*                                          0          0
Abscess of thymus                                           0          0
Abscess or ulceration of vulva                              0          0
Absence of iris [Aniridia]                                  0          0
Abuse of non-psychoactive substances*                       0          0
Acantholytic Disorders*                                     0          0
Acanthosis nigricans                                        0          0
Accessory auricle                                           0          0
Accessory kidney*                                           0          0
Accessory lobe of lung*                                     0          0
Accommodative esotropia                                     0          0
Acetonuria                                                  0          0
Achalasia of cardia                                         0          0
Achilles tendinitis                                         0          0
Achlorhydria                                                0          0
Achondroplasia*                                             0          0
Acidosis                                                    0          0
Acne                                                        0          0
Acquired atrophy of ovary and fallopian tube                0          0
Acquired clawhand                                           0          0
Acquired clubhand                                           0          0
Acquired coagulation factor deficiency                      0          0
Acquired deformities of fingers                             0          0
Acquired deformities of fingers and toes                    0          0
Acquired deformities of limbs                               0          0
Acquired deformities of the ankle and foot                  0          0
Acquired deformities of the forearm and hand                0          0
Acquired deformities of toe                                 0          0
Acquired periventricular cysts of newborn*                  0          0
Acquired pure red cell aplasia [erythroblastopenia]          0          0
Acromioclavicular (joint) (ligament) sprain                 0          0
Actinic keratosis                                           0          0
Actinic reticuloid and actinic granuloma                    0          0
Actinomyces and Nocardia                                    0          0
Activated Phosphoinositide 3-kinase Delta Syndrome [APDS]          0          0
Activated protein C resistance*                             0          0
Acute (transverse) myelitis                                 0          0
Acute Pharyngitis                                           0          0
Acute bronchiolitis                                         0          0
Acute bronchitis                                            0          0
Acute chest syndrome                                        0          0
Acute cholecystitis                                         0          0
Acute cough*                                                0          0
Acute cystitis                                              0          0
Acute dermatitis due to solar radiation                     0          0
Acute dilatation of stomach                                 0          0
Acute disseminated encephalitis and encephalomyelitis (ADEM)          0          0
Acute epiglottitis                                          0          0
Acute gastritis                                             0          0
Acute hepatitis                                             0          0
Acute hepatitis C                                           0          0
Acute idiopathic pulmonary hemorrhage in infants            0          0
Acute inflammatory pelvic disease                           0          0
Acute intermittent (hepatic) porphyria*                     0          0
Acute kidney failure                                        0          0
Acute laryngitis and tracheitis                             0          0
Acute leukemia                                              0          0
Acute lower respiratory infection                           0          0
Acute lymphadenitis                                         0          0
Acute lymphoid leukemia                                     0          0
Acute myeloid leukemia                                      0          0
Acute myocardial infarction                                 0          0
Acute nasopharyngitis                                       0          0
Acute nephritic syndrome                                    0          0
Acute obstructive laryngitis [croup]                        0          0
Acute pain                                                  0          0
Acute pancreatitis                                          0          0
Acute posthemorrhagic anemia                                0          0
Acute prostatitis                                           0          0
Acute pulmonary heart disease                               0          0
Acute pyelonephritis                                        0          0
Acute respiratory distress syndrome [ARDS]*                 0          0
Acute respiratory failure                                   0          0
Acute sinusitis                                             0          0
Acute skin changes due to ultraviolet radiation             0          0
Acute thyroiditis                                           0          0
Acute tonsillitis and adenoiditis                           0          0
Acute upper respiratory infection                           0          0
Acute vascular insufficiency of intestine                   0          0
Acute/subacute osteomyelitis                                0          0
Adenosine deaminase 2 deficiency (DADA2)*                   0          0
Adenovirus                                                  0          0
Adhesions and ankylosis of temporomandibular joint          0          0
Adhesions and disruptions of iris and ciliary body          0          0
Adhesive capsulitis of shoulder                             0          0
Adhesive middle ear disease [Glue ear]                      0          0
Adrenal hyperfunction                                       0          0
Adrenocortical insufficiency                                0          0
Adrenogenital disorders                                     0          0
Adrenoleukodystrophy*                                       0          0
Age-related cognitive decline                               0          0
Age-related macular degeneration                            0          0
Agenesis and underdevelopment of nose*                      0          0
Agenesis of ureter*                                         0          0
Aggressive periodontitis                                    0          0
Agoraphobia                                                 0          0
Ainhum                                                      0          0
Albinism*                                                   0          0
Alcohol abuse and dependence                                0          0
Alcohol use disorders                                       0          0
Alcohol use during pregnancy*                               0          0
Alcoholic cardiomyopathy                                    0          0
Alcoholic hepatitis                                         0          0
Alcoholic liver disease                                     0          0
Alkalosis                                                   0          0
Alkalosis of newborn*                                       0          0
Allergic and dietetic gastroenteritis and colitis           0          0
Allergic bronchopulmonary aspergillosis                     0          0
Allergic conjunctivitis                                     0          0
Allergic dermatitis of eyelid                               0          0
Allergic purpura [Henoch-Schoenlein purpura]                0          0
Allergic rhinitis                                           0          0
Allergic rhinitis due to food                               0          0
Allergic rhinitis, due to animal hair and dander            0          0
Allergic urticaria                                          0          0
Allergies related to other diseases/symptoms                0          0
Allergy                                                     0          0
Allergy to analgesic agent                                  0          0
Allergy to anesthetic agent                                 0          0
Allergy to antibiotic agent (excluding penicillin)          0          0
Allergy to food additives                                   0          0
Allergy to fruits and vegetables                            0          0
Allergy to insects                                          0          0
Allergy to narcotic agent                                   0          0
Allergy to other anti-infective agents                      0          0
Allergy to radiographic dye                                 0          0
Allergy to serum and vaccine                                0          0
Allergy to sulfonamides                                     0          0
Alopecia                                                    0          0
Alopecia Areata                                             0          0
Alpers disease*                                             0          0
Alpha thalassemia                                           0          0
Alpha-1-antitrypsin deficiency                              0          0
Alport syndrome*                                            0          0
Alteration of consciousness                                 0          0
Altered mental status, unspecified                          0          0
Alternating esotropia                                       0          0
Alternating exotropia                                       0          0
Alveolar proteinosis                                        0          0
Alveolitis of jaw                                           0          0
Alzheimer's disease                                         0          0
Amblyopia                                                   0          0
Amebiasis                                                   0          0

### A3.2. Out of those 5 diseases, we now label the prognosis into improving, stable, worsening, mixed, or no_comparison

In [ ]:
prognosis_main([
    "--reports", str(path1),
    "--patients", str(patients_path),
    "--out", str(prognosis_path),
])

Read 100/2857 reports
Read 200/2857 reports
Read 300/2857 reports
Read 400/2857 reports
Read 500/2857 reports
Read 600/2857 reports
Read 700/2857 reports
Read 800/2857 reports
Read 900/2857 reports
Read 1000/2857 reports
Read 1100/2857 reports
Read 1200/2857 reports
Read 1300/2857 reports
Read 1400/2857 reports
Read 1500/2857 reports
Read 1600/2857 reports
Read 1700/2857 reports
Read 1800/2857 reports
Read 1900/2857 reports
Read 2000/2857 reports
Read 2100/2857 reports
Read 2200/2857 reports
Read 2300/2857 reports
Read 2400/2857 reports
Read 2500/2857 reports
Read 2600/2857 reports
Read 2700/2857 reports
Read 2800/2857 reports
Saved 14285 disease-study rows and 11755 candidate targets to C:\Users\Zila\Downloads\BN5212\midterm_prognosis\labelling\prognosis_labels
Verify comparison references and fill reviewed_target before training. Split by subject_id.

In [57]:
diseases = [
    "Pleural effusion",
    "Cardiomegaly",
    "Edema",
    "Pneumonia",
    "Pulmonary edema",
]

In [ ]:
prognosis.main([
    "--reports", str(path1),
    "--patients", str(patients_path),
    "--labels", str(labels_path),
    "--reviews", str(reviews_path),
    "--mode", "lenient",
    "--out", str(hybrid_path),
])

Read 100/2857 reports
Read 200/2857 reports
Read 300/2857 reports
Read 400/2857 reports
Read 500/2857 reports
Read 600/2857 reports
Read 700/2857 reports
Read 800/2857 reports
Read 900/2857 reports
Read 1000/2857 reports
Read 1100/2857 reports
Read 1200/2857 reports
Read 1300/2857 reports
Read 1400/2857 reports
Read 1500/2857 reports
Read 1600/2857 reports
Read 1700/2857 reports
Read 1800/2857 reports
Read 1900/2857 reports
Read 2000/2857 reports
Read 2100/2857 reports
Read 2200/2857 reports
Read 2300/2857 reports
Read 2400/2857 reports
Read 2500/2857 reports
Read 2600/2857 reports
Read 2700/2857 reports
Read 2800/2857 reports
Saved 14285 disease-study rows and 11755 candidate targets to C:\Users\Zila\Downloads\BN5212\midterm_prognosis\labelling\prognosis_labels_hybrid
Verify comparison references and fill reviewed_target before training. Split by subject_id.

In [67]:
pairs = pd.read_csv(hybrid_path / "prognosis_pairs.csv")

existing_disease = pairs[
    pairs["input_disease_state"].eq("positive")
]

display(pd.crosstab(
    existing_disease["disease"],
    existing_disease["candidate_target"],
).reindex(
    columns=["improving", "stable", "worsening", "mixed", "no_comparison"],
    fill_value=0,
))

candidate_target  improving  stable  worsening  mixed  no_comparison
disease
Cardiomegaly              4      82         14      1            208
Edema                    64      20         25      2            209
Pleural effusion         58      54         47     12            190
Pneumonia                27       4          9      1            144
Pulmonary edema          53      16         20      1            156

## A4. Now that we have labeled, we will load training, validation, and test sets

In [71]:
from data_loader.cxr_prognosis_dataloader import make_dataloaders

loaders = make_dataloaders(
    pairs_csv=hybrid_path / "prognosis_pairs.csv",
    disease="Pleural effusion",
    reports_root=path1,
    batch_size=16,
    image_size=224,
    num_workers=0,  # Suitable for Windows notebooks
    seed=42,
    positive_input_only=True,
    use_candidates=True,  # Exploratory baseline using automatic labels
    split_csv=labelling_dir / "prognosis_patient_splits.csv",
    manifest_path=hybrid_path / "pleural_effusion_image_manifest.csv",
)

train_loader = loaders["train"]
val_loader = loaders["val"]
test_loader = loaders["test"]

train {'patients': 63, 'samples': 128, 'improving': 45, 'stable': 47, 'worsening': 36}
val {'patients': 11, 'samples': 13, 'improving': 7, 'stable': 2, 'worsening': 4}
test {'patients': 8, 'samples': 18, 'improving': 6, 'stable': 5, 'worsening': 7}
Excluded: {'input_not_positive': 1990, 'unreviewed_or_nontraining_label': 202}

In [74]:
from data_loader.cxr_backbone_dataloader import make_backbone_dataloaders

backbone_loaders = make_backbone_dataloaders(
    labels_csv=labels_path,
    reviews_csv=reviews_path,
    report_summary_csv=output_path / "report_summary.csv",
    split_csv=labelling_dir / "prognosis_patient_splits.csv",
    reports_root=path1,
    batch_size=16,
    image_size=224,
    num_workers=0,
    manifest_path=labelling_dir / "backbone_image_manifest.csv",
)

backbone_train_loader = backbone_loaders["train"]
backbone_val_loader = backbone_loaders["val"]
backbone_test_loader = backbone_loaders["test"]

train studies: 2008 patients: 354
val studies: 307 patients: 74
test studies: 392 patients: 77
Excluded: {'unusable_report': 150}

### A4.1. In

In [77]:
import torch
from model.cxr_backbone import CXRBackbone, diagnosis_loss

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = CXRBackbone(pretrained=True).to(device)

batch = next(iter(backbone_train_loader))
images = batch["image"].to(device)
targets = batch["targets"].to(device)

logits = model(images)
loss = diagnosis_loss(logits, targets)

print(logits.shape)  # [B, 5, 4]
print(loss.item())

3.6%

Downloading: "https://download.pytorch.org/models/densenet121-a639ec97.pth" to C:\Users\Zila/.cache\torch\hub\checkpoints\densenet121-a639ec97.pth

100.0%

torch.Size([16, 5, 4])
1.4523804187774658

In [79]:
import sys
import torch

print("Python:", sys.executable)
print("PyTorch:", torch.__version__)
print("CUDA build:", torch.version.cuda)
print("CUDA available:", torch.cuda.is_available())
print("GPU count:", torch.cuda.device_count())

Python: c:\Users\Zila\miniconda3\envs\longitudinal_progression\python.exe
PyTorch: 2.14.1+cpu
CUDA build: None
CUDA available: False
GPU count: 0

In [80]:
!nvidia-smi

Sat Oct  3 01:29:14 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 591.91                 Driver Version: 591.91         CUDA Version: 13.1     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                  Driver-Model | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 5060 ...  WDDM  |   00000000:01:00.0  On |                  N/A |
| N/A   46C    P5              6W /   70W |     482MiB /   8151MiB |     19%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A           22980    C+G   C:\Windows\explorer.exe               N/A      |
+-----------------------------------------------------------------------------------------+

In [78]:
from datetime import datetime
import torch

from model.cxr_backbone import CXRBackbone
from model.train_backbone import train_backbone

# Seed before initializing the model
torch.manual_seed(42)

model = CXRBackbone(pretrained=True)

run_dir = (
    project_dir / "training_outputs"
    / datetime.now().strftime("backbone_%Y%m%d_%H%M%S")
)

results = train_backbone(
    model=model,
    loaders=backbone_loaders,
    out_dir=run_dir,
    epochs=20,
    learning_rate=1e-4,
    weight_decay=1e-4,
)

Device: cpu | Epochs: 20 | Learning rate: 0.0001

KeyboardInterrupt:

In [1]:
import torch

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))
    x = torch.ones(3, device="cuda")
    print("GPU calculation:", (x * 2).cpu())

PyTorch: 2.14.1+cu130
CUDA available: True
GPU: NVIDIA GeForce RTX 5060 Laptop GPU
GPU calculation: tensor([2., 2., 2.])